networks:
  ismile-deploy-net:
    name: ismile-deploy-net
    driver: bridge

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     #  - ./db_data:/var/lib/postgresql/data
      # - /mnt/disks/db_data/eeats-db-dev:/var/lib/postgresql/data
      - /mnt/secondary/dbdata:/var/lib/postgresql/data
      # - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    networks:
      - ismile-deploy-net
    ports:
      - "5577:5432"
    environment:
      - TZ=Asia/Jakarta

  api:
    container_name: ismilelab-api-prod
    depends_on:
      - db
    image: ismilelab/ismile-website:api
    env_file:
      - .env.api
    volumes:
      - ./wwwroot/upload:/app/wwwroot/upload
    restart: unless-stopped
    networks:
      - ismile-deploy-net
    environment:
      - TZ=Asia/Jakarta

  web:
    container_name: ismilelab-web-prod
    depends_on:
      - api
    image: ismilelab/ismile-website:web
    env_file:
      - .env.web
    restart: unless-stopped
    ports:
      - "4568:8080"
    networks:
      - ismile-deploy-net

  tunnel:
    container_name: cl-tun-ismile-web
    depends_on:
      - web
    image: cloudflare/cloudflared
    restart: unless-stopped
    # command: tunnel run --token 
    command: tunnel run
    env_file:
      - .env.tunnel
    networks:
      - ismile-deploy-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
