networks:
  ismile-deploy-net:
    name: ismile-deploy-net
    driver: bridge

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     #  - ./db_data:/var/lib/postgresql/data
      # - /mnt/disks/db_data/eeats-db-dev:/var/lib/postgresql/data
      - /mnt/secondary/dbdata:/var/lib/postgresql/data
      # - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql
    networks:
      - ismile-deploy-net
    ports:
      - "5577:5432"
